version: '3.3'
services:
  unpub:
    build: ./
    container_name: unpub
    restart: always
    ports:
      - 4000:4000
    volumes: 
      - ~/.unpub-packages:/app/unpub-packages
    depends_on:
      - mongo
  mongo: 
    image: mongo:5.0.8
    container_name: mongo 
    restart: always
    volumes: 
      - ~/.mongo:/data/db